[project]
name = "random-images-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zxxhz", email = "ou0897@foxmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
random-images-api = "random_images_api:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
