[project]
name = "random-douni-api"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "zxxhz", email = "ou0897@foxmail.com"},
]
dependencies = [
    "fastapi[standard]>=0.141.1",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
